tasks:
  - name: Remix App
    init: |
      cd incredible-website
      npm i

    command: |
      cd incredible-website
      npm run dev

  - name: Docker Compose
    command: docker-compose -f docker-compose.yml up
    openMode: split-right

ports:
  - port: 3000 # website
    onOpen: open-preview
  - port: 8080 # flipt
    onOpen: open-preview
  - port: 8002
    onOpen: ignore
  - port: 9000
    onOpen: ignore
