services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - back-tier

  flipt:
    image: flipt/flipt:latest
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - ./flipt:/var/opt/flipt